name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run end to end test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Build action
        run: npm run build
      - name: Run local dot-npmrc action
        uses: ./
        with:
          root: '.'
          org: 'example-org'
          registry: 'npm.pkg.github.com'
          token: 'example-token'
      - name: Check if the result is correct
        run: cmp --silent .npmrc .npmrc.example || echo "Result is incorrect."

